import { getListSocialMessagesQueryKey, useCreateSocialMessage, useListSocialMessages } from '@workspace/api-client-react';
import { useLocalSearchParams } from 'expo-router';
import React, { useRef, useState } from 'react';
import { FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { KeyboardAvoidingView } from 'react-native-keyboard-controller';
import { AppScreen, Avatar, BackButton, ErrorState, LoadingState } from '@/components/ui';
import { useColors } from '@/hooks/useColors';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function ConversationScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const conversationId = String(id); const messages = useListSocialMessages(conversationId, { query: { queryKey: getListSocialMessagesQueryKey(conversationId) } }); const send = useCreateSocialMessage(); const [body, setBody] = useState(''); const input = useRef<TextInput>(null);
  const submit = () => { const value = body.trim(); if (!value || send.isPending) return; send.mutate({ conversationId, data: { body: value } }, { onSuccess: () => { setBody(''); void messages.refetch(); input.current?.focus(); } }); };
  if (messages.isLoading) return <AppScreen scroll={false}><LoadingState /></AppScreen>; if (messages.isError || !messages.data) return <AppScreen scroll={false}><ErrorState onRetry={() => void messages.refetch()} /></AppScreen>;
  const items = [...messages.data.items].reverse();
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.background }} behavior="padding" keyboardVerticalOffset={0}><View style={{ flex: 1, paddingTop: insets.top + 14 }}><View style={{ paddingHorizontal: 18, paddingBottom: 12 }}><BackButton /></View><FlatList data={items} inverted keyExtractor={(message) => message.id} keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingHorizontal: 18, paddingBottom: 12, gap: 8 }} renderItem={({ item: message }) => <View style={{ alignSelf: 'flex-end', maxWidth: '84%', backgroundColor: colors.secondary, borderRadius: 16, padding: 12 }}><Text style={{ color: colors.secondaryForeground, lineHeight: 20 }}>{message.body}</Text><Text style={{ color: colors.mutedForeground, fontSize: 10, marginTop: 4 }}>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></View>} /><View style={{ flexDirection: 'row', gap: 8, alignItems: 'flex-end', padding: 12, paddingBottom: insets.bottom + 8, borderTopWidth: 1, borderTopColor: colors.border }}><TextInput ref={input} value={body} onChangeText={setBody} placeholder="Napisz wiadomość…" placeholderTextColor={colors.mutedForeground} multiline style={{ flex: 1, maxHeight: 100, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 12, color: colors.foreground }} /><Pressable disabled={!body.trim() || send.isPending} onPress={submit} style={{ padding: 13, borderRadius: 14, backgroundColor: colors.primary, opacity: !body.trim() ? 0.5 : 1 }}><Text style={{ color: colors.primaryForeground, fontFamily: 'Inter_700Bold' }}>Wyślij</Text></Pressable></View></View></KeyboardAvoidingView>;
}